[versions]
kotlin = "2.0.20"
kotlinx-coroutines = "1.9.0"
fritz2 = "1.0-RC20"
ksp = "2.0.20-1.0.25"

npm-tailwindcss = "3.4.18"
npm-tailwindcss-forms = "0.5.10"

npm-postcss = "8.5.6"
npm-postcss-loader = "8.2.0"
npm-autoprefixer = "10.4.22"
npm-cssloader = "7.1.2"
npm-cssnano = "7.1.2"
npm-minicssextractplugin = "2.9.4"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
fritz2-headless = { group = "dev.fritz2", name = "headless", version.ref = "fritz2" }
fritz2-lensesprocessor = { group = "dev.fritz2", name = "lenses-annotation-processor", version.ref = "fritz2" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }